service: serverless-example

plugins:
  - serverless-esbuild
  # - serverless-bundle
  - serverless-offline

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x

custom:
  # bundle:
  #   packager: yarn
  #   sourcemaps: true
  #   externals:                      # Set non Webpack compatible packages as externals
  #     - lodash
  esbuild:
    packager: yarn
    bundle: true
    minify: true
    sourcemap: true
    keepNames: true
    external:
      - lodash


functions:
  hello1:
    handler: hello1.handler
    events:
      - http:
          path: hello1
          method: get

  hello2:
    handler: hello2.handler
    events:
      - http:
          path: hello2
          method: get
